# Generated by Django 2.2.1 on 2019-05-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190515_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('contactno', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('nofc', models.IntegerField()),
            ],
        ),
    ]
