# Generated by Django 2.2.1 on 2019-05-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20190515_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='contactno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
