# Generated by Django 2.2.1 on 2019-05-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_reserve_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='date',
        ),
        migrations.AddField(
            model_name='reserve',
            name='book_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserve',
            name='last_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
