# Generated by Django 2.2.1 on 2019-05-16 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20190516_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='book_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
