# Generated by Django 2.2.1 on 2019-05-16 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20190516_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='book_date',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='last_date',
        ),
    ]
